# Generated by Django 5.2 on 2025-04-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_staff_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff_email',
        ),
    ]
