# Generated by Django 5.2 on 2025-04-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_staff_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff_email',
            new_name='StaffEmail',
        ),
    ]
