export const AllTrainData = [
  {
    id: 1,
    name: "Rajdhani Express",
    number: "12301",
    status: "Running",
  },
  {
    id: 2,
    name: "Shatabdi Express",
    number: "12001",
    status: "Cancelled",
  },
  {
    id: 3,
    name: "Duronto Express",
    number: "12245",
    status: "Running",
  },
  {
    id: 4,
    name: "Garib Rath Express",
    number: "12910",
    status: "Running",
  },
  {
    id: 5,
    name: "Jan Shatabdi Express",
    number: "12052",
    status: "Cancelled",
  },
  {
    id: 6,
    name: "Intercity Express",
    number: "12737",
    status: "Running",
  },
  {
    id: 7,
    name: "Superfast Express",
    number: "12905",
    status: "Running",
  },
  {
    id: 8,
    name: "Tejas Express",
    number: "22671",
    status: "Cancelled",
  },
  {
    id: 9,
    name: "Double Decker Express",
    number: "12931",
    status: "Running",
  },
  {
    id: 10,
    name: "Humsafar Express",
    number: "22920",
    status: "Running",
  },
  {
    id: 11,
    name: "Vande Bharat Express",
    number: "22436",
    status: "Running",
  },
  {
    id: 12,
    name: "Antyodaya Express",
    number: "22877",
    status: "Cancelled",
  },
  {
    id: 13,
    name: "Uday Express",
    number: "22665",
    status: "Running",
  },
  {
    id: 14,
    name: "Sampark Kranti Express",
    number: "12649",
    status: "Cancelled",
  },
  {
    id: 15,
    name: "Yuva Express",
    number: "12249",
    status: "Running",
  },
  {
    id: 16,
    name: "Mahamana Express",
    number: "22418",
    status: "Running",
  },
  {
    id: 17,
    name: "Sampoorna Kranti Express",
    number: "12394",
    status: "Running",
  },
];
