# Generated by Django 5.2 on 2025-04-04 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coach_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=50)),
                ('train_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('seat_type', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=10)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.coach')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.seat')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.train')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.train'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('created_at', models.DateField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.ticket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ticket',), name='unique_ticket')],
            },
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat', 'date', 'train', 'coach'), name='unique_seat'),
        ),
    ]
