# Generated by Django 5.2 on 2025-04-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0002_ticket_destination_ticket_starting_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_number',
        ),
    ]
