// passengerData.js

export const passengerData = [
  {
    pnr: "PNR001",
    passengers: [{ seat: "A1" }, { seat: "A2" }],
    coach: "SL",
    source: "Delhi",
    destination: "Mumbai",
    bookedBy: "Rahul Verma",
    contact: "9876543210",
  },
  {
    pnr: "PNR002",
    passengers: [{ seat: "B1" }],
    coach: "3AC",
    source: "Chennai",
    destination: "Bangalore",
    bookedBy: "John Doe",
    contact: "9123456780",
  },
  {
    pnr: "PNR003",
    passengers: [{ seat: "C1" }, { seat: "C2" }, { seat: "C3" }],
    coach: "2AC",
    source: "Kolkata",
    destination: "Patna",
    bookedBy: "Rita Sen",
    contact: "9812312345",
  },
  {
    pnr: "PNR004",
    passengers: [{ seat: "D1" }],
    coach: "SL",
    source: "Lucknow",
    destination: "Varanasi",
    bookedBy: "Amit Singh",
    contact: "9090909090",
  },
  {
    pnr: "PNR005",
    passengers: [{ seat: "E1" }, { seat: "E2" }],
    coach: "1AC",
    source: "Hyderabad",
    destination: "Delhi",
    bookedBy: "Priya Sharma",
    contact: "8888888888",
  },
  {
    pnr: "PNR006",
    passengers: [{ seat: "F1" }],
    coach: "3AC",
    source: "Pune",
    destination: "Ahmedabad",
    bookedBy: "Neha Mehta",
    contact: "9876501234",
  },
  {
    pnr: "PNR007",
    passengers: [{ seat: "G1" }, { seat: "G2" }],
    coach: "SL",
    source: "Nagpur",
    destination: "Bhopal",
    bookedBy: "Vikram Patel",
    contact: "9999999999",
  },
  {
    pnr: "PNR008",
    passengers: [{ seat: "H1" }],
    coach: "2AC",
    source: "Coimbatore",
    destination: "Madurai",
    bookedBy: "Raman Iyer",
    contact: "9321678945",
  },
  {
    pnr: "PNR009",
    passengers: [{ seat: "I1" }, { seat: "I2" }, { seat: "I3" }],
    coach: "1AC",
    source: "Guwahati",
    destination: "Shillong",
    bookedBy: "Megha Roy",
    contact: "9819891981",
  },
  {
    pnr: "PNR010",
    passengers: [{ seat: "J1" }],
    coach: "3AC",
    source: "Jaipur",
    destination: "Udaipur",
    bookedBy: "Ravi Rathore",
    contact: "9786543210",
  },
  {
    pnr: "PNR011",
    passengers: [{ seat: "K1" }, { seat: "K2" }],
    coach: "SL",
    source: "Surat",
    destination: "Rajkot",
    bookedBy: "Amit Chauhan",
    contact: "9797979797",
  },
  {
    pnr: "PNR012",
    passengers: [{ seat: "L1" }],
    coach: "2AC",
    source: "Amritsar",
    destination: "Jalandhar",
    bookedBy: "Simran Kaur",
    contact: "9012345678",
  },
  {
    pnr: "PNR013",
    passengers: [{ seat: "M1" }, { seat: "M2" }, { seat: "M3" }, { seat: "M4" }],
    coach: "3AC",
    source: "Kanpur",
    destination: "Allahabad",
    bookedBy: "Arjun Tiwari",
    contact: "9900112233",
  },
  {
    pnr: "PNR014",
    passengers: [{ seat: "N1" }],
    coach: "1AC",
    source: "Bhubaneswar",
    destination: "Kharagpur",
    bookedBy: "Rohit Das",
    contact: "9324567890",
  },
  {
    pnr: "PNR015",
    passengers: [{ seat: "O1" }, { seat: "O2" }],
    coach: "SL",
    source: "Ranchi",
    destination: "Jamshedpur",
    bookedBy: "Kavita Singh",
    contact: "9870012345",
  },
];
