# Generated by Django 5.2 on 2025-04-07 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('job_role_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('job_role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('job_role_id', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_reported', models.TextField()),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.jobschedule')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobschedule',
            constraint=models.UniqueConstraint(fields=('train_id', 'date', 'employee'), name='unique_record'),
        ),
    ]
