# Generated by Django 5.2 on 2025-04-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobschedule',
            name='issue',
        ),
    ]
