# Generated by Django 5.2 on 2025-04-07 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('ticketbooking', '0003_review_unique_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.jobrole'),
        ),
        migrations.AlterField(
            model_name='jobschedule',
            name='train_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.train'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('user', 'job_role_id'), name='unique_employee'),
        ),
    ]
